### ISSUE TITLE
Display Sections

### ISSUE THREAD

**Issue by ryanbarsatan** [manoa-dojo/manoa-dojo#5]
Ryan
- Pull data from Section collection
- Display data
- Expand button shows description of the section

**Comment by ryanbarsatan** [comment]
Xen

**Comment by XenHuang** [comment]
I did it already.

**Comment by XenHuang** [comment]
Oh except the expand button. Couldn't figure it out. Used a popup message instead.

**Comment by ryanbarsatan** [comment]
ok cool thanks
